In [4]:
import torch
import numpy as np
from erfa import dt_pv

print("np.version:",np.__version__)
print("torch.version:",torch.__version__)

np.version: 1.26.4
torch.version: 2.7.1


In [1]:
a = torch.tensor([
    [1, 2],
    [3, 4]
], dtype=torch.int32)
b = torch.rand(size=(3, 4, 9))
c = torch.zeros_like(b)

NameError: name 'torch' is not defined

In [37]:
b = torch.linspace(2, 10, 4)
shuffle_idx = torch.randperm(len(b))
shuffle_b = b[shuffle_idx]

In [55]:
dev = torch.device("cpu")
value = torch.tensor([1, 2, 3], device=dev)
idx = torch.tensor([[0, 1, 2],[0, 1, 2], [0, 1, 2]], device=dev)
stride_arr = torch.sparse_coo_tensor(idx, value, (3, 3, 3), device=dev)

In [90]:
tmp = torch.rand((5, 2)) + torch.rand(2)

In [92]:
print(torch.floor(tmp))#向下取整
print(torch.ceil(tmp))#向上取整
print(torch.round(tmp))#四舍五入
print(torch.trunc(tmp))#截断 只取整数部分
print(torch.frac(tmp))#取小数部分

tensor([[1., 1.],
        [1., 0.],
        [0., 1.],
        [1., 1.],
        [1., 0.]])
tensor([[2., 2.],
        [2., 1.],
        [1., 2.],
        [2., 2.],
        [2., 1.]])
tensor([[2., 1.],
        [1., 1.],
        [1., 1.],
        [1., 2.],
        [2., 1.]])
tensor([[1., 1.],
        [1., 0.],
        [0., 1.],
        [1., 1.],
        [1., 0.]])
tensor([[0.6033, 0.3455],
        [0.4860, 0.9324],
        [0.8016, 0.4833],
        [0.3053, 0.5960],
        [0.5998, 0.9319]])


In [106]:
tmp_1, _ = torch.sort(tmp, dim=1)
print(torch.topk(tmp, 1, dim=1)[0])
finate = -finate


tensor([[1.6033],
        [1.4860],
        [1.4833],
        [1.5960],
        [1.5998]])


In [109]:
tmp2 = torch.rand((5, 2))

In [135]:
out = torch.where(tmp2 > 0.5, tmp2, tmp)
out = torch.gather(tmp, dim = 1, index=torch.tensor([[1, 0, 1, 0, 1]]))
out = torch.stack((tmp, tmp), dim=1)

In [132]:
help(torch.stack)

Help on built-in function stack in module torch:

stack(...)
    stack(tensors, dim=0, *, out=None) -> Tensor

    Concatenates a sequence of tensors along a new dimension.

    All tensors need to be of the same size.

    .. seealso::

        :func:`torch.cat` concatenates the given sequence along an existing dimension.

    Arguments:
        tensors (sequence of Tensors): sequence of tensors to concatenate
        dim (int, optional): dimension to insert. Has to be between 0 and the number
            of dimensions of concatenated tensors (inclusive). Default: 0

    Keyword args:
        out (Tensor, optional): the output tensor.

    Example::

        >>> x = torch.randn(2, 3)
        >>> x
        tensor([[ 0.3367,  0.1288,  0.2345],
                [ 0.2303, -1.1229, -0.1863]])
        >>> torch.stack((x, x)) # same as torch.stack((x, x), dim=0)
        tensor([[[ 0.3367,  0.1288,  0.2345],
                 [ 0.2303, -1.1229, -0.1863]],

                [[ 0.3367,  0.1288,  0